In [2]:
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (40.11.0)

In [3]:
from faker import Faker
import pandas as pd

In [4]:
class Person:
    def __init__(self, name, age, address, phone, job):
        self.name = name
        self.age = age
        self.address = address
        self.phone = phone
        self.job = job

In [5]:
fake = Faker()

In [6]:
people = []

for i in range(1000):
    person = Person(
        fake.name(),
        fake.random_int(min=18, max=60),
        fake.address(),
        fake.phone_number(),
        fake.job()
    )

    people.append({
        "Name": person.name,
        "Age": person.age,
        "Address": person.address,
        "Phone": person.phone,
        "Job": person.job
    })

In [7]:
df = pd.DataFrame(people)

In [8]:
print("Total data:", len(df))

df.head()

Total data: 1000

,Name,Age,Address,Phone,Job
0,Courtney Boone,31,"0400 Hanson Stravenue Suite 739\nKendraton, VI...",938.515.9945x472,Theme park manager
1,Melissa Hall,50,"7087 Tonya Islands\nPort Joestad, TX 52225",001-599-836-9713,Building services engineer
2,Steven Yang,20,"6431 John Ways Apt. 887\nLowefurt, HI 36534",367-444-0819,Learning disability nurse
3,Anthony Castro,45,"86337 Gregory Brook Apt. 887\nPort Jennifer, A...",635-672-8486x346,Financial controller
4,Matthew Allen,25,Unit 7561 Box 6830\nDPO AP 07219,341-656-4184x2279,Air broker

In [9]:
df.describe()

               Age
count  1000.000000
mean     39.257000
std      12.624117
min      18.000000
25%      28.000000
50%      39.000000
75%      50.250000
max      60.000000